import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import {ClerkProvider} from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VoyageVision - An AI powered Tour app",
  description: "Generated by create next app",
};



export default function RootLayout({children}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main style={{ fontFamily: "monospace" }}>
            <Providers>{children}</Providers>
          </main>
        </body>
      </html>
    </ClerkProvider>

  );
}